export const NAVBAR_BUTTONS = {
    EXPLORE: 'NAVBAR_BUTTONS/EXPLORE',
    DISCOVER: 'NAVBAR_BUTTONS/DISCOVER',
    RESOURCES: 'NAVBAR_BUTTONS/RESOURCES',
    BLOG: 'NAVBAR_BUTTONS/BLOG',
    BIM_CO: 'NAVBAR_BUTTONS/BIM_CO',
};