export const COLORS = {
    TEXT: '#42526E',
    BUTTON_TEXT_HOVERED: '#0075F6',
    BUTTON_BACKGROUND: '#FFFFFF',
    BUTTON_BACKGROUND_HOVERED: 'rgba(0, 117, 246, 0.1)',
    CTA_TEXT: '#FFFFFF',
    CTA_TEXT_HOVERED: '#FFFFFF',
    CTA_BACKGROUND: '#0075F6',
    CTA_BACKGROUND_HOVERED: '#0F2073',
};

export const FONT_SIZES = {
    TEXT: '14px',
    TITLE: '24px',
};

export const FONT_WEIGHTS = {
    BOLD: 700,
}
